BUTTERY(1)
==========
:doctype: manpage


NAME
----
buttery - creates backups of Btrfs subvolumes and more


SYNOPSIS
--------
*buttery* ['OPTIONS'] 'SNAPDIR' ['SUBVOLUME' ...]


DESCRIPTION
-----------
*buttery* creates and manages backups of Btrfs filesystems by creating snapshots of subvolumes.

It can use `'btrfs send'` to send the created backups to other Btrfs filesystems or remote servers, and can automatically thin out old backups.


OPTIONS
-------
=== GENERAL OPTIONS ===
*--help*::
  Show this help and exit

*-n*, *--dry-run*::
  Explain what would be done, without actually doing anything

*-v*, *--verbose*::
  Print more operation messages, particularly about purge selection

=== REMOTE OPTIONS ===
*-r*, *--remote*='PATH'::
  Path to use as `'btrfs receive'` destination

*-c*, *--remote-command*='COMMAND'::
  Path to the `'btrfs'` command for `'btrfs receive'` +
  (Default: `'btrfs'`, see the *<<EXAMPLES,Examples>>* section)

*-N*, *--remote-name*='NAME'::
  Name of the remote connection, used to identify different remote locations +
  (Default: `'remote'`, see the *<<EXAMPLES,Examples>>* section)

=== PURGING OPTIONS ===
*-p*, *--purge*[='NAME']::
  Purge old snapshots that match `'NAME'`. +
  (See the *<<PURGE,Purging Backups>>* section)

*-h*, *--hourly*='DAYS'::
  Keep hourly backups until they are 'DAYS' days old. +
  (Default: `1`, implies *--purge*)

*-d*, *--daily*='DAYS'::
  Keep daily backups until they are 'DAYS' days old. +
  (Default: `14`, implies *--purge*)

*-w*, *--weekly*='DAYS'::
  Keep weekly backups until they are 'DAYS' days old. +
  (Default: `90`, implies *--purge*)

*-m*, *--monthly*='DAYS'::
  Keep monthly backups until they are 'DAYS' days old. +
  (Default: `365`, implies *--purge*)

*-y*, *--yearly*='DAYS'::
  Keep annual backups until they are 'DAYS' days old. +
  (Default: `730`, implies *--purge*)


POSITIONAL ARGUMENTS
--------------------
*SNAPDIR*::
  Where *buttery* will store locally created backups.

*SUBVOLUME*::
  A list of subvolumes to back up.


SNAPSHOT NAMING
---------------
Snapshot names will consist of the subvolume "name" (from `'btrfs subvolume show'`), and the date/time.
For example, `'/mnt/users'` might be `'users_YYYYmmdd-HHMMSS'`.

A symlink to the most recent backup is maintained at `'SNAPDIR/NAME_latest'`.
The most recent successful remote send is at `'SNAPDIR/NAME_latest_REMOTENAME'`.

CAUTION: Beware of duplicate subvolume names.


[[PURGE]]
PURGING BACKUPS
---------------
When using *--purge*, the *--hourly*, *--daily*, *--weekly*, *--monthly*, and *--yearly* options control the cutoff age for backups in days.
All purge-related options imply *--purge*.

If you do not want backups of a particular slot, set that cutoff to `'0'`.

*--purge* can be used with an optional 'NAME' to only consider snapshots with that name for purging.
*--purge='NAME'* can be specified multiple times to purge multiple selected names at once.

Snapshots with a `'*_latest*'` symlink pointing to them will not be removed.

Any snapshots in the backup directory matching the naming convention will be considered for purging.
If you want to keep a particular backup forever, simply make sure there is a `'*_latest*'` symlink pointing to it.

To see which snapshots will be purged and why, run `'buttery'` with the `'--verbose --dry-run'` options.

[[EXAMPLES]]
EXAMPLES
--------
Say you have Btrfs subvolumes at `'/'` and `'/home'`, and you want to store backups in `'/mnt/backups'`:

  # buttery /mnt/backups / /home

This will result in a set of snapshots and links like this:

  /mnt/backups/root_20220102-124500
  /mnt/backups/root_latest -> root_20220102-124500
  /mnt/backups/home_20220102-124500
  /mnt/backups/home_latest -> home_20220102-124500

The next time you run this command, it will create another set of backup snapshots and update the `'*_latest*'` symlinks accordingly.

To create local backups in `'/mnt/backups'` and also `'btrfs send'` them to a Btrfs filesystem on `'/mnt/usb'`:

  # buttery --remote=/mnt/usb /mnt/backups / /home

To send backups to a remote server, use `'--remote-cmd'`:

  # buttery --remote-cmd='ssh root@backups.example.com btrfs' \
            --remote=/mnt/backups /mnt/snaps / /home

When sending snapshots to a remote filesystem, `'$NAME_latest_$REMOTENAME'` symlinks will be created.

When working with multiple remote filesystems, the *--remote-name* option can be used to differentiate between them.
This helps keep the latest remote snapshots for multiple destinations pinned, so you can always do an incremental send.

  # buttery --remote-name=blue --remote=/mnt/usb /mnt/backups / /home

  /mnt/backups/home_20220102-124500
  /mnt/backups/home_20220103-163030
  /mnt/backups/home_latest -> home_20220103-163030
  /mnt/backups/home_latest_red -> home_20220102-124500
  /mnt/backups/home_latest_blue -> home_20220103-163030

To thin out old backups in `'/mnt/backups'` without creating any new backups:

  # buttery --purge /mnt/backups

CAUTION: This can also be run on the remote filesystem to thin out your remote snapshots.
However, without symlinks to pin snapshots on the remote filesystem, you can accidentally purge your common parent snapshot.
I recommend symlinking your latest common snapshot on the remote filesystem to remedy this.
Unfortunately, `'buttery'` cannot do this for you yet.


BUGS
----
Unfortunately, there are some limitations at the moment, mostly due to limited command access to remote servers.

Check the bug tracker at https://github.com/ZDBioHazard/buttery/issues and please report any other issues you may have.
